[build]
  command = "echo 'No build step required for PHP application'"
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/api/:splat.php"
  status = 200

[[redirects]]
  from = "/*"
  to = "/:splat.php"
  status = 200

[build.environment]
  PHP_VERSION = "8.2"
